# Generated by Django 4.2.9 on 2024-03-09 16:12

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='HistoricalCategoryProduct',
            fields=[
                ('basemodel_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='base.basemodel')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.BooleanField(default=True)),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='fecha de creacion ')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Descripcion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical category product',
                'verbose_name_plural': 'historical category products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicador',
            fields=[
                ('basemodel_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='base.basemodel')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.BooleanField(default=True)),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='fecha de creacion ')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('discount_value', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical indicador',
                'verbose_name_plural': 'historical indicadors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeasureUnit',
            fields=[
                ('basemodel_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='base.basemodel')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.BooleanField(default=True)),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='fecha de creacion ')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Descripcion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical measure unit',
                'verbose_name_plural': 'historical measure units',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('basemodel_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='base.basemodel')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.BooleanField(default=True)),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='fecha de creacion ')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Nombre de producto')),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de producto')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('discount_value', models.PositiveSmallIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Indicador de oferta')),
            ],
            bases=('base.basemodel',),
        ),
    ]
